services:
  - type: web
    name: real-estate-chatbot
    env: python
    buildCommand: ""
    startCommand: "python app.py"
    envVars:
      - key: OPENROUTER_API_KEY
        value: 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
